### PR TITLE
C and OCaml bindings for Tapir

### PR DESCRIPTION
**Pull request by Willtor**
When you wish upon a star, makes no difference who you are.  Because in space, no one can hear you scream.

### CODE REVIEW

**Comment by neboat** [comment]
I'm excited to see these additions.  The changes looks good to me.  Do you have a test case handy for verifying that these changes work?

**Comment by Willtor** [comment]
I don't have anything small that tests them.  DEF will use these changes as soon as they're ready.  I can commit and push those changes, though I was planning on doing it in the opposite order.  Is that what we need?

**Comment by Willtor** [comment]
Okay!  I've created a tapir-transition branch to DEF:
https://github.com/Willtor/def/tree/tapir-transition
And I added the c28866e changeset that works with that branch (and fixes a missing macro bug).

**Review by wsmoses — DISMISSED** [review]
LGTM, though yeah at one point some unit tests would be nice.

**Comment by wsmoses** [comment]
Sorry, apparently CI wasn't configured properly for PR's from external forks, if you don't mind repushing to trigger a build (and then you'll be able to merge once the build passes).

**Comment by Willtor** [comment]
I'll add the OCaml stuff into the unit tests for it.  That'll cover the C bindings, too, since OCaml uses them.  When I push that change, will that trigger the build?

**Comment by Willtor** [comment]
Like a boss!

**Review by wsmoses — APPROVED** [review]

**Pull request merged**
